-- MySQL Script generated by MySQL Workbench
-- Fri Mar 24 21:10:41 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `cnpj` VARCHAR(45) NOT NULL,
  `razaoSocial` VARCHAR(200) NULL,
  `nomeFantasia` VARCHAR(200) NULL,
  `capitalSocial` VARCHAR(45) NULL,
  `empresa_MeEppMei` INT NULL,
  `primeira_compra` DATETIME NULL,
  `totalAtivo` FLOAT(20,2) NULL,
  `totalPatrimonioLiquido` FLOAT(20,2) NULL,
  `faturamentoBruto` FLOAT(20,2) NULL,
  `anoFundacao` INT NULL,
  `senha` VARCHAR(100) NOT NULL DEFAULT '123',
  `periodoBalanco` DATETIME NULL,
  `prazoMedioRecebimentoVendas` INT NULL,
  `titulosEmAberto` FLOAT(20,2) NULL,
  `periodoDemonstrativoEmMeses` INT NULL,
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC) VISIBLE,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Emprestimo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Emprestimo` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `valorSolicitado` FLOAT(20,2) NULL,
  `valorAprovado` FLOAT(20,2) NULL,
  `status` VARCHAR(100) NULL,
  `dataAprovadoEmComite` DATETIME NULL,
  `dataAprovadoNivelAnalista` DATETIME NULL,
  `id_cliente` INT(10) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `CLIENTE_EMPRESTIMO_idx` (`id_cliente` ASC) VISIBLE,
  CONSTRAINT `CLIENTE_EMPRESTIMO`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `mydb`.`Cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`External_Token`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`External_Token` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_cliente` INT(10) NULL,
  `token` VARCHAR(100) NULL,
  `dataCriacao` DATETIME NULL,
  `dataExpiracao` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `Cliente_Token_idx` (`id_cliente` ASC) VISIBLE,
  CONSTRAINT `Cliente_Token`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `mydb`.`Cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Emprestimo_Mensagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Emprestimo_Mensagem` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `id_emprestimo` INT(10) NOT NULL,
  `mensagem` VARCHAR(1000) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_emprestimo_UNIQUE` (`id_emprestimo` ASC) VISIBLE,
  CONSTRAINT `emprestimo_mensagem`
    FOREIGN KEY (`id_emprestimo`)
    REFERENCES `mydb`.`Emprestimo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
